name: test

on:
  push:
    branches: [main, beta]
  pull_request:
    branches: [main, beta]
  schedule:
    # run daily at 00:00
    - cron: 0 0 * * *

jobs:
  get-playwright-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: get-versions
        with:
          script: |
            const minimalVersion = '1.34';
            const { execSync } = require('node:child_process');
            const info = execSync('npm show --json @playwright/test').toString();
            const { versions } = JSON.parse(info);
            return versions
              .filter((v) => v.match(/\.0$/) && v >= minimalVersion)
              .map((v) => v.replace(/\.0$/, ''))
              .concat([ 'beta' ]);
    outputs:
      versions: ${{ steps.get-versions.outputs.result }}

  test:
    needs: get-playwright-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        playwrightVersion: ${{ fromJson(needs.get-playwright-versions.outputs.versions) }}
        cucumberVersion: ['9']
        include:
          # there were breaking changes in cucumber 10.x -> test on 10.0 and 10.1
          - playwrightVersion: '1.37'
            cucumberVersion: '10.0'
          - playwrightVersion: '1.38'
            cucumberVersion: '10.1'
          - playwrightVersion: '1.39'
            cucumberVersion: '10.3'
          - playwrightVersion: '1.40'
            cucumberVersion: '10'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: >
          npm install
          @playwright/test@${{ matrix.playwrightVersion }}
          @playwright/experimental-ct-react@${{ matrix.playwrightVersion }}
          @cucumber/cucumber@${{ matrix.cucumberVersion }}

      - run: npx playwright install --with-deps chromium
      - run: npm test
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results-${{ matrix.playwrightVersion }}-${{ matrix.cucumberVersion }}
          path: |
            test/**/test-results/
            test/**/actual-reports/
            test/**/blob-report/ 
            test/**/.features-gen/
          retention-days: 1
          if-no-files-found: ignore
