name: test-win

on:
  push:

jobs:
  test-win:
    runs-on: windows-latest
    strategy:
      matrix:
        cucumberVersion: ['9', '10']
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm install @cucumber/cucumber@${{ matrix.cucumberVersion }}
      - run: npx playwright install --with-deps chromium
      - name: run tests
        run: |
          # don't use 'npm t' here as it doesn't expand filename wildcards
          node test/setup.mjs
          node --test test/**/test.mjs
          # this command gets all test files in powershell
          # node --test $(Get-ChildItem -Path test -Recurse -Include test.mjs).FullName
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test/**/test-results/
          retention-days: 10
          if-no-files-found: ignore
