# Running all tests on win always hangs-up.
# This is possibly related to deadlocks due node --test subprocesses + Playwright supprocesses
# Keep this file with single test just to have at least something on win.
# Also you can create custom branch with particular test to check on win.
# See: https://github.com/actions/runner/issues/1326#issuecomment-1172283561
name: test-win

on:
  push:

jobs:
  test-win:
    runs-on: windows-latest
    strategy:
      matrix:
        cucumberVersion: ['9', '10']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm install @playwright/test@1.36 @cucumber/cucumber@${{ matrix.cucumberVersion }}
      - run: npx playwright install --with-deps chromium
      - name: run tests
        env:
          FORBID_ONLY: 1
        run: |
          node test/setup.mjs
          node test/bdd-syntax/test.mjs
          node test/snippets-playwright-style/test.mjs
        # this command gets all test files in powershell
        # node --test $(Get-ChildItem -Path test -Recurse -Include test.mjs).FullName
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test/**/test-results/
          retention-days: 10
          if-no-files-found: ignore
