name: test

on:
  push:

jobs:
  get-playwright-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: get-versions
        with:
          script: return ['1.32', '1.33', '1.34', '1.35']
    outputs:
      versions: ${{ steps.get-versions.outputs.result }}

  test:
    needs: get-playwright-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        playwrightVersion: ${{ fromJson(needs.get-playwright-versions.outputs.versions) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm install @playwright/test@${{ matrix.playwrightVersion }}
      - run: npx playwright install --with-deps chromium
      - run: FORBID_ONLY=1 npm test
